# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [9]:
# Create a 1-dimensional NumPy array using np.array()

arr_2D = np.array([1,2,3])
# Create a 2-dimensional NumPy array using np.array()
arr_2D = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
arr_3D = np.array([[[1, 2], [3, 4]],[[1,2],[3,4]]])



Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [10]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print("shape", arr_1D.shape  )
print("number of dimensions", arr_1D.ndim  )
print("data type", arr_1D.dtype  )
print("size", arr_1D.size  )
print("tupe", type(arr_1D) )


shape (3,)
number of dimensions 1
data type int32
size 3
tupe <class 'numpy.ndarray'>


In [11]:
# Attributes of 2-dimensional array
print("shape", arr_2D.shape  )
print("number of dimensions", arr_2D.ndim  )
print("data type", arr_2D.dtype  )
print("size", arr_2D.size  )
print("tupe", type(arr_2D) )

shape (2, 3)
number of dimensions 2
data type int32
size 6
tupe <class 'numpy.ndarray'>


In [12]:
# Attributes of 3-dimensional array
print("shape", arr_3D.shape  )
print("number of dimensions", arr_3D.ndim  )
print("data type", arr_3D.dtype  )
print("size", arr_3D.size  )
print("tupe", type(arr_3D) )

shape (2, 2, 2)
number of dimensions 3
data type int32
size 8
tupe <class 'numpy.ndarray'>


In [15]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(arr_2D)
df

0  1  2
0  1  2  3
1  4  5  6

In [17]:
# Create an array of shape (10, 2) with only ones
arr = np.ones((10,2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# Create an array of shape (7, 2, 3) of only zeros
arr = np.zeros((7,2,3))
arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
# Create an array within a range of 0 and 100 with step 3
arr = np.arange(0,100,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [23]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr = np.random.randint(0,10,size=(7,2))
arr

array([[8, 1],
       [9, 7],
       [3, 6],
       [6, 9],
       [9, 3],
       [3, 0],
       [3, 4]])

In [26]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr = np.random.uniform(0,1,size=(3,5))
arr

array([[0.59769019, 0.82812371, 0.38197344, 0.91146131, 0.30445162],
       [0.43329653, 0.59393504, 0.36594232, 0.61997499, 0.00940336],
       [0.74303436, 0.8116999 , 0.67347669, 0.22473317, 0.42490814]])

In [30]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr = np.random.randint(0,10,size=(4,6))
arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [33]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable

arr = np.random.randint(1,10,size=(3,7))
print(arr)
# Find the unique numbers in the array you just created
np.unique(arr)

[[2 5 8 9 9 1 9]
 [7 9 8 1 8 8 3]
 [1 8 3 3 1 5 7]]


array([1, 2, 3, 5, 7, 8, 9])

In [36]:
# Find the 0'th index of the latest array you created
arr[0,0]

2

In [37]:
# Get the first 2 rows of latest array you created
arr[:2,:]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [38]:
# Get the first 2 values of the first 2 rows of the latest array
arr[:2,:2]

array([[2, 5],
       [7, 9]])

In [44]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr_rand = np.random.randint(1,10,size=(3,5))
arr_ones = np.ones((3,5))
print(arr_rand)
print("\n",arr_ones)

[[1 1 2 2 6]
 [7 5 1 1 3]
 [2 5 6 7 4]]

 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [45]:
# Add the two arrays together
arr_add = arr_rand + arr_ones
arr_add

array([[2., 2., 3., 3., 7.],
       [8., 6., 2., 2., 4.],
       [3., 6., 7., 8., 5.]])

In [46]:
# Create another array of ones of shape (5, 3)
arr_ones2 = np.ones((5,3))


In [47]:
# Try add the array of ones and the other most recent array together
arr_add2 = arr_ones2 + arr_ones


ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?different shapes

How would you fix it?transpose one of them

In [51]:
# Create another array of ones of shape (3, 5)
arr_ones3 = np.ones((3,5))


In [54]:
# Subtract the new array of ones from the other most recent array
arr_sub = arr_add - arr_ones3  
arr_sub

array([[1., 1., 2., 2., 6.],
       [7., 5., 1., 1., 3.],
       [2., 5., 6., 7., 4.]])

In [57]:
# Multiply the ones array with the latest array
arr_mult = arr_sub * arr_ones3 
arr_mult

array([[1., 1., 2., 2., 6.],
       [7., 5., 1., 1., 3.],
       [2., 5., 6., 7., 4.]])

In [59]:
# Take the latest array to the power of 2 using '**'
arr_pwr = arr_mult ** 2
arr_pwr

array([[ 1.,  1.,  4.,  4., 36.],
       [49., 25.,  1.,  1.,  9.],
       [ 4., 25., 36., 49., 16.]])

In [58]:
# Do the same thing with np.square()
arr_pwr2 = np.square(arr_mult )
arr_pwr2

array([[ 1.,  1.,  4.,  4., 36.],
       [49., 25.,  1.,  1.,  9.],
       [ 4., 25., 36., 49., 16.]])

In [61]:
# Find the mean of the latest array using np.mean()
mean = np.mean(arr_pwr2)
mean

17.4

In [63]:
# Find the maximum of the latest array using np.max()
maximum = np.max(arr_pwr2)
maximum

49.0

In [65]:
# Find the minimum of the latest array using np.min()
minimum = np.min(arr_pwr2)
minimum

1.0

In [66]:
# Find the standard deviation of the latest array
std = np.std(arr_pwr2)
std

17.304334717058612

In [67]:
# Find the variance of the latest array
var = np.var(arr_pwr2)
var

299.44

In [72]:
# Reshape the latest array to (3, 5, 1)
new_arr = arr_pwr2.reshape(3,5,1)
new_arr

array([[[ 1.],
        [ 1.],
        [ 4.],
        [ 4.],
        [36.]],

       [[49.],
        [25.],
        [ 1.],
        [ 1.],
        [ 9.]],

       [[ 4.],
        [25.],
        [36.],
        [49.],
        [16.]]])

In [74]:
# Transpose the latest array
trans_arr = new_arr.T
trans_arr

array([[[ 1., 49.,  4.],
        [ 1., 25., 25.],
        [ 4.,  1., 36.],
        [ 4.,  1., 49.],
        [36.,  9., 16.]]])

What does the transpose do?swap rows and columns


In [75]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
rand_arr1 = np.random.randint(0, 10, size=(3, 3))
rand_arr2 = np.random.randint(0, 10, size=(3, 2))

In [76]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(rand_arr1, rand_arr2)
dot_product

array([[86, 35],
       [89, 47],
       [33, 20]])

In [77]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
rand_arr1 = np.random.randint(0, 10, size=(4, 3))
rand_arr2 = np.random.randint(0, 10, size=(4, 3))

In [78]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(rand_arr1, rand_arr2)
dot_product

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?transpose one of them

In [79]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
dot_product = np.dot(rand_arr1, rand_arr2.T)
dot_product

array([[ 17,  49,  54, 108],
       [ 16,  35,  36,  54],
       [ 27,  80,  79, 127],
       [ 49,  62,  75, 111]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [110]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1 = np.random.randint(0, 10, size=(4, 3))
arr2 = np.random.randint(0, 10, size=(4, 3))
print(arr1)
print("\n",arr2)

[[6 1 9]
 [1 9 0]
 [7 0 8]
 [5 6 9]]

 [[6 9 2]
 [1 8 7]
 [9 6 8]
 [3 3 0]]


In [111]:
# Compare the two arrays with '>'
arr1 > arr2

array([[False, False,  True],
       [False,  True, False],
       [False, False, False],
       [ True,  True,  True]])

What happens when you compare the arrays with `>`?

In [112]:
# Compare the two arrays with '>='
arr1 >= arr2

array([[ True, False,  True],
       [ True,  True, False],
       [False, False,  True],
       [ True,  True,  True]])

In [113]:
# Find which elements of the first array are greater than 7
arr1 > 7

array([[False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True]])

In [114]:
# Which parts of each array are equal? (try using '==')
arr1 == arr2

array([[ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False, False, False]])

In [115]:
# Sort one of the arrays you just created in ascending order
sorted_arr1 = np.sort(arr1)
sorted_arr1

array([[1, 6, 9],
       [0, 1, 9],
       [0, 7, 8],
       [5, 6, 9]])

OR

In [116]:
# Sort one of the arrays you just created in ascending order
sorted2_arr1 = np.sort(arr1,axis = None)
sorted2_arr1

array([0, 0, 1, 1, 5, 6, 6, 7, 8, 9, 9, 9])

In [117]:
# Sort the indexes of one of the arrays you just created
sorted_idx1 = np.argsort(arr1)
sorted_idx1

array([[1, 0, 2],
       [2, 0, 1],
       [1, 0, 2],
       [0, 1, 2]], dtype=int64)

OR

In [118]:
# Sort the indexes of one of the arrays you just created
sorted2_idx1 = np.argsort(arr1,axis = None)
sorted2_idx1

array([ 5,  7,  1,  3,  9,  0, 10,  6,  8,  2,  4, 11], dtype=int64)

In [119]:
# Find the index with the maximum value in one of the arrays you've created
max_idx =np.unravel_index(np.argmax(arr1, axis=None), arr1.shape)
max_idx

(0, 2)

In [120]:
# Find the index with the minimum value in one of the arrays you've created
min_idx = np.unravel_index(np.argmin(arr1, axis=None), arr1.shape)
min_idx

(1, 2)

In [121]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_idxs = np.argmax(arr1, axis = 1)
max_idxs

array([2, 1, 2, 2], dtype=int64)

In [122]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_idxs = np.argmin(arr1, axis = 0)
min_idxs

array([1, 2, 1], dtype=int64)

In [126]:
# Create an array of normally distributed random numbers
normal_arr = np.random.normal(loc  = 0, scale = 1,size =  (4,3))
normal_arr

array([[-0.54128544,  0.776823  , -0.04764371],
       [ 0.51869446, -0.39140181,  0.4380226 ],
       [ 1.66376979, -0.73923643, -0.10719448],
       [-0.48621729,  1.59298179, -0.4339416 ]])

In [127]:
# Create an array with 10 evenly spaced numbers between 1 and 100
even_spaced_arr = np.linspace(1, 100, 10)
even_spaced_arr

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.